# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_inquery.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql

class Ui_MainWindow(object):
    def beforeSetupUi(self, MainWindow):
        self.mysql = pymysql.connect(host='localhost',port=3306,user='root',passwd='',db='library')
        print("mysql conn")
        cursor = self.mysql.cursor()
        cursor.execute("select * from area;");
        result = cursor.fetchone()
        while(result):
            print(result)
            result=cursor.fetchone()

    def setupUi(self, MainWindow):
        self.beforeSetupUi(MainWindow);
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(845, 600)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtUserid = QtWidgets.QLineEdit(self.centralwidget)
        self.txtUserid.setGeometry(QtCore.QRect(30, 20, 151, 31))
        self.txtUserid.setText("")
        self.txtUserid.setObjectName("txtUserid")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 60, 221, 161))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 40, 71, 16))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 71, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 71, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 71, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(100, 130, 101, 16))
        self.label_5.setText("")
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(100, 70, 101, 16))
        self.label_6.setText("")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(100, 100, 101, 16))
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(100, 40, 101, 16))
        self.label_8.setText("")
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 20, 71, 32))
        self.pushButton.setObjectName("pushButton")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(310, 17, 58, 16))
        self.label_9.setObjectName("label_9")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(260, 50, 561, 181))
        self.treeWidget.setWordWrap(True)
        self.treeWidget.setColumnCount(7)
        self.treeWidget.setObjectName("treeWidget")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/books.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.treeWidget.headerItem().setIcon(2, icon)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("image/note.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.treeWidget.headerItem().setIcon(6, icon1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.treeWidget.header().setVisible(False)
        self.treeWidget.header().setDefaultSectionSize(70)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(270, 10, 32, 32))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("image/books.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(270, 280, 32, 32))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("image/deadline.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(310, 288, 58, 16))
        self.label_12.setObjectName("label_12")
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget_2.setGeometry(QtCore.QRect(260, 320, 561, 181))
        self.treeWidget_2.setObjectName("treeWidget_2")
        self.treeWidget_2.headerItem().setText(0, "1")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 320, 221, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 39, 112, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 110, 112, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_27 = QtWidgets.QLabel(self.groupBox_2)
        self.label_27.setGeometry(QtCore.QRect(30, 50, 32, 32))
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("image/open-book.png"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setGeometry(QtCore.QRect(30, 120, 32, 32))
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("image/reservation.png"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.pagePrev1 = QtWidgets.QLabel(self.centralwidget)
        self.pagePrev1.setGeometry(QtCore.QRect(410, 230, 50, 50))
        self.pagePrev1.setText("")
        self.pagePrev1.setPixmap(QtGui.QPixmap("image/square.png"))
        self.pagePrev1.setScaledContents(True)
        self.pagePrev1.setObjectName("pagePrev1")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(420, 240, 30, 30))
        self.label_13.setAutoFillBackground(False)
        self.label_13.setStyleSheet("background-color: rgb(252, 61, 197);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(570, 240, 30, 30))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.pagePrev1_3 = QtWidgets.QLabel(self.centralwidget)
        self.pagePrev1_3.setGeometry(QtCore.QRect(560, 230, 50, 50))
        self.pagePrev1_3.setText("")
        self.pagePrev1_3.setPixmap(QtGui.QPixmap("image/square.png"))
        self.pagePrev1_3.setScaledContents(True)
        self.pagePrev1_3.setObjectName("pagePrev1_3")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(520, 240, 30, 30))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.pagePrev1_4 = QtWidgets.QLabel(self.centralwidget)
        self.pagePrev1_4.setGeometry(QtCore.QRect(510, 230, 50, 50))
        self.pagePrev1_4.setText("")
        self.pagePrev1_4.setPixmap(QtGui.QPixmap("image/square.png"))
        self.pagePrev1_4.setScaledContents(True)
        self.pagePrev1_4.setObjectName("pagePrev1_4")
        self.pagePrev1_7 = QtWidgets.QLabel(self.centralwidget)
        self.pagePrev1_7.setGeometry(QtCore.QRect(460, 230, 50, 50))
        self.pagePrev1_7.setText("")
        self.pagePrev1_7.setPixmap(QtGui.QPixmap("image/square.png"))
        self.pagePrev1_7.setScaledContents(True)
        self.pagePrev1_7.setObjectName("pagePrev1_7")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(470, 240, 30, 30))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.pagePrev1_8 = QtWidgets.QLabel(self.centralwidget)
        self.pagePrev1_8.setGeometry(QtCore.QRect(610, 230, 50, 50))
        self.pagePrev1_8.setText("")
        self.pagePrev1_8.setPixmap(QtGui.QPixmap("image/square.png"))
        self.pagePrev1_8.setScaledContents(True)
        self.pagePrev1_8.setObjectName("pagePrev1_8")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(620, 240, 30, 30))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.pagePrev1_9 = QtWidgets.QLabel(self.centralwidget)
        self.pagePrev1_9.setGeometry(QtCore.QRect(510, 500, 50, 50))
        self.pagePrev1_9.setText("")
        self.pagePrev1_9.setPixmap(QtGui.QPixmap("image/square.png"))
        self.pagePrev1_9.setScaledContents(True)
        self.pagePrev1_9.setObjectName("pagePrev1_9")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(570, 510, 30, 30))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(470, 510, 30, 30))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(520, 510, 30, 30))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.pagePrev1_11 = QtWidgets.QLabel(self.centralwidget)
        self.pagePrev1_11.setGeometry(QtCore.QRect(610, 500, 50, 50))
        self.pagePrev1_11.setText("")
        self.pagePrev1_11.setPixmap(QtGui.QPixmap("image/square.png"))
        self.pagePrev1_11.setScaledContents(True)
        self.pagePrev1_11.setObjectName("pagePrev1_11")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(420, 510, 30, 30))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.pagePrev1_2 = QtWidgets.QLabel(self.centralwidget)
        self.pagePrev1_2.setGeometry(QtCore.QRect(410, 500, 50, 50))
        self.pagePrev1_2.setText("")
        self.pagePrev1_2.setPixmap(QtGui.QPixmap("image/square.png"))
        self.pagePrev1_2.setScaledContents(True)
        self.pagePrev1_2.setObjectName("pagePrev1_2")
        self.pagePrev1_12 = QtWidgets.QLabel(self.centralwidget)
        self.pagePrev1_12.setGeometry(QtCore.QRect(460, 500, 50, 50))
        self.pagePrev1_12.setText("")
        self.pagePrev1_12.setPixmap(QtGui.QPixmap("image/square.png"))
        self.pagePrev1_12.setScaledContents(True)
        self.pagePrev1_12.setObjectName("pagePrev1_12")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(620, 510, 30, 30))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.pagePrev1_13 = QtWidgets.QLabel(self.centralwidget)
        self.pagePrev1_13.setGeometry(QtCore.QRect(560, 500, 50, 50))
        self.pagePrev1_13.setText("")
        self.pagePrev1_13.setPixmap(QtGui.QPixmap("image/square.png"))
        self.pagePrev1_13.setScaledContents(True)
        self.pagePrev1_13.setObjectName("pagePrev1_13")
        self.label_13.raise_()
        self.pagePrev1_3.raise_()
        self.pagePrev1_4.raise_()
        self.pagePrev1_7.raise_()
        self.label_19.raise_()
        self.txtUserid.raise_()
        self.groupBox.raise_()
        self.pushButton.raise_()
        self.label_9.raise_()
        self.treeWidget.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.treeWidget_2.raise_()
        self.groupBox_2.raise_()
        self.pagePrev1.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.pagePrev1_8.raise_()
        self.label_20.raise_()
        self.pagePrev1_9.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.pagePrev1_11.raise_()
        self.label_14.raise_()
        self.pagePrev1_2.raise_()
        self.pagePrev1_12.raise_()
        self.label_26.raise_()
        self.pagePrev1_13.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 845, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txtUserid.setPlaceholderText(_translate("MainWindow", "Userid"))
        self.groupBox.setTitle(_translate("MainWindow", "사용자 정보"))
        self.label.setText(_translate("MainWindow", "이름 :"))
        self.label_2.setText(_translate("MainWindow", "사용자 번호 :"))
        self.label_3.setText(_translate("MainWindow", "연체권수 :"))
        self.label_4.setText(_translate("MainWindow", "대여권수 :"))
        self.pushButton.setText(_translate("MainWindow", "조회"))
        self.label_9.setText(_translate("MainWindow", "대여현황"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "No"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "등록번호"))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "제목"))
        self.treeWidget.headerItem().setText(3, _translate("MainWindow", "대여시작일"))
        self.treeWidget.headerItem().setText(4, _translate("MainWindow", "반납예정일"))
        self.treeWidget.headerItem().setText(5, _translate("MainWindow", "연체일"))
        self.treeWidget.headerItem().setText(6, _translate("MainWindow", "메모"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "1"))
        self.treeWidget.topLevelItem(0).setText(1, _translate("MainWindow", "1"))
        self.treeWidget.topLevelItem(0).setText(2, _translate("MainWindow", "물은 답을 알고 있다"))
        self.treeWidget.topLevelItem(0).setText(3, _translate("MainWindow", "2019-12-04"))
        self.treeWidget.topLevelItem(0).setText(4, _translate("MainWindow", "2019-12-07"))
        self.treeWidget.topLevelItem(0).setText(5, _translate("MainWindow", "0"))
        self.treeWidget.topLevelItem(0).setText(6, _translate("MainWindow", "상습연체자"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.label_12.setText(_translate("MainWindow", "연체현황"))
        self.groupBox_2.setTitle(_translate("MainWindow", "사서 관리"))
        self.pushButton_2.setText(_translate("MainWindow", "대출"))
        self.pushButton_3.setText(_translate("MainWindow", "예약"))
        self.label_13.setText(_translate("MainWindow", "<"))
        self.label_15.setText(_translate("MainWindow", "3"))
        self.label_16.setText(_translate("MainWindow", "2"))
        self.label_19.setText(_translate("MainWindow", "1"))
        self.label_20.setText(_translate("MainWindow", ">"))
        self.label_22.setText(_translate("MainWindow", "3"))
        self.label_23.setText(_translate("MainWindow", "1"))
        self.label_24.setText(_translate("MainWindow", "2"))
        self.label_14.setText(_translate("MainWindow", "<"))
        self.label_26.setText(_translate("MainWindow", ">"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
